# Configuraci√≥n de MercadoSkyblock

# Aqu√≠ se guardar√°n autom√°ticamente las ventas para el sistema de oferta/demanda.
# No necesitas editar esto manualmente.
ventas: {}

# =========================
# üì¶ CATEGOR√çAS DEL MERCADO
# =========================
categorias:

  AGRICULTURA:
    - WHEAT
    - WHEAT_SEEDS
    - CARROT
    - POTATO
    - POISONOUS_POTATO
    - BEETROOT
    - BEETROOT_SEEDS
    - MELON_SLICE
    - MELON
    - MELON_SEEDS
    - PUMPKIN
    - PUMPKIN_SEEDS
    - SUGAR_CANE
    - BAMBOO
    - CACTUS
    - KELP
    - DRIED_KELP
    - COCOA_BEANS
    - SWEET_BERRIES
    - GLOW_BERRIES
    - NETHER_WART
    - CHORUS_FRUIT
    - POPPED_CHORUS_FRUIT
    - CHORUS_FLOWER
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    - MUSHROOM_STEM
    - CRIMSON_FUNGUS
    - WARPED_FUNGUS
    - VINE
    - WEEPING_VINES
    - TWISTING_VINES
    - LILY_PAD
    - SMALL_DRIPLEAF
    - BIG_DRIPLEAF
    - MOSS_BLOCK
    - MOSS_CARPET
    - SPORE_BLOSSOM
    - HANGING_ROOTS
    - AZALEA
    - FLOWERING_AZALEA
    - TORCHFLOWER_SEEDS
    - PITCHER_POD
    - HAY_BLOCK

  COMIDA:
    - BEEF
    - COOKED_BEEF
    - PORKCHOP
    - COOKED_PORKCHOP
    - CHICKEN
    - COOKED_CHICKEN
    - MUTTON
    - COOKED_MUTTON
    - RABBIT
    - COOKED_RABBIT
    - COD
    - COOKED_COD
    - SALMON
    - COOKED_SALMON
    - PUFFERFISH
    - TROPICAL_FISH
    - APPLE
    - HONEY_BOTTLE

  MOBS:
    - ROTTEN_FLESH
    - BONE
    - BONE_MEAL
    - STRING
    - SPIDER_EYE
    - FERMENTED_SPIDER_EYE
    - GUNPOWDER
    - ENDER_PEARL
    - BLAZE_ROD
    - BLAZE_POWDER
    - GHAST_TEAR
    - MAGMA_CREAM
    - MAGMA_BLOCK
    - SLIME_BALL
    - SLIME_BLOCK
    - PHANTOM_MEMBRANE
    - SHULKER_SHELL
    - WITHER_SKELETON_SKULL
    - FEATHER
    - LEATHER
    - INK_SAC
    - GLOW_INK_SAC
    - EGG
    - ARROW
    - TOTEM_OF_UNDYING
    - SCUTE

  MADERAS:
    - OAK_LOG
    - SPRUCE_LOG
    - BIRCH_LOG
    - JUNGLE_LOG
    - ACACIA_LOG
    - DARK_OAK_LOG
    - MANGROVE_LOG
    - CHERRY_LOG
    - CRIMSON_STEM
    - WARPED_STEM
    - STRIPPED_OAK_LOG
    - STRIPPED_SPRUCE_LOG
    - STRIPPED_BIRCH_LOG
    - STRIPPED_JUNGLE_LOG
    - STRIPPED_ACACIA_LOG
    - STRIPPED_DARK_OAK_LOG
    - STRIPPED_MANGROVE_LOG
    - STRIPPED_CHERRY_LOG
    - STRIPPED_CRIMSON_STEM
    - STRIPPED_WARPED_STEM
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - MANGROVE_PLANKS
    - CHERRY_PLANKS
    - CRIMSON_PLANKS
    - WARPED_PLANKS
    - OAK_LEAVES
    - SPRUCE_LEAVES
    - BIRCH_LEAVES
    - JUNGLE_LEAVES
    - ACACIA_LEAVES
    - DARK_OAK_LEAVES
    - MANGROVE_LEAVES
    - CHERRY_LEAVES
    - OAK_SAPLING
    - SPRUCE_SAPLING
    - BIRCH_SAPLING
    - JUNGLE_SAPLING
    - ACACIA_SAPLING
    - DARK_OAK_SAPLING
    - MANGROVE_PROPAGULE
    - CHERRY_SAPLING
    - STICK

  MINERALES:
    - COAL
    - CHARCOAL
    - COAL_BLOCK
    - IRON_INGOT
    - IRON_NUGGET
    - RAW_IRON
    - IRON_ORE
    - DEEPSLATE_IRON_ORE
    - IRON_BLOCK
    - COPPER_INGOT
    - RAW_COPPER
    - COPPER_ORE
    - DEEPSLATE_COPPER_ORE
    - COPPER_BLOCK
    - GOLD_INGOT
    - GOLD_NUGGET
    - RAW_GOLD
    - GOLD_ORE
    - DEEPSLATE_GOLD_ORE
    - GOLD_BLOCK
    - REDSTONE
    - REDSTONE_BLOCK
    - LAPIS_LAZULI
    - LAPIS_BLOCK
    - DIAMOND
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
    - DIAMOND_BLOCK
    - EMERALD
    - EMERALD_ORE
    - DEEPSLATE_EMERALD_ORE
    - EMERALD_BLOCK
    - QUARTZ
    - AMETHYST_SHARD
    - AMETHYST_BLOCK
    - NETHERITE_SCRAP
    - NETHERITE_INGOT
    - FLINT

  PIEDRAS:
    - COBBLESTONE
    - STONE
    - SMOOTH_STONE
    - GRANITE
    - POLISHED_GRANITE
    - DIORITE
    - POLISHED_DIORITE
    - ANDESITE
    - POLISHED_ANDESITE
    - CALCITE
    - TUFF
    - DEEPSLATE
    - COBBLED_DEEPSLATE
    - POLISHED_DEEPSLATE
    - DEEPSLATE_TILES
    - DEEPSLATE_BRICKS
    - DRIPSTONE_BLOCK
    - POINTED_DRIPSTONE
    - OBSIDIAN
    - GRAVEL
    - SAND
    - RED_SAND
    - SANDSTONE
    - CUT_SANDSTONE
    - CUT_SANDSTONE_SLAB
    - SANDSTONE_SLAB
    - SANDSTONE_STAIRS
    - RED_SANDSTONE
    - CUT_RED_SANDSTONE
    - CUT_RED_SANDSTONE_SLAB
    - RED_SANDSTONE_SLAB
    - RED_SANDSTONE_STAIRS
    - BASALT
    - BLACKSTONE
    - NETHERRACK
    - END_STONE
    - END_STONE_BRICKS
    - PURPUR_BLOCK
    - PURPUR_SLAB
    - PURPUR_STAIRS

  CONSTRUCCION:
    - DIRT
    - GRASS_BLOCK
    - PODZOL
    - MYCELIUM
    - COARSE_DIRT
    - MUD
    - PACKED_MUD
    - SNOWBALL
    - SNOW_BLOCK
    - ICE
    - PACKED_ICE
    - BLUE_ICE
    - GLASS
    - GLASS_PANE
    - TERRACOTTA
    - BRICKS
    - STONE_BRICKS
    - CRACKED_STONE_BRICKS
    - CHISELED_STONE_BRICKS
    - PRISMARINE
    - PRISMARINE_BRICKS
    - DARK_PRISMARINE
    - PRISMARINE_SHARD
    - PRISMARINE_CRYSTALS
    - SEA_LANTERN
    - SPONGE
    - BEACON
    - CONDUIT