# Configuraci√≥n de MercadoSkyblock

# Aqu√≠ se guardar√°n autom√°ticamente las ventas para el sistema de oferta/demanda.
ventas: {}

# =========================
# üí∞ PRECIOS BASE
# =========================
precios:

  # AGRICULTURA
  WHEAT: 2.0
  WHEAT_SEEDS: 0.2
  CARROT: 2.5
  POTATO: 2.5
  POISONOUS_POTATO: 0.3
  BEETROOT: 2.0
  BEETROOT_SEEDS: 0.2
  MELON_SLICE: 0.4
  MELON: 3.0
  MELON_SEEDS: 0.2
  PUMPKIN: 4.0
  PUMPKIN_SEEDS: 0.2
  SUGAR_CANE: 1.5
  BAMBOO: 0.5
  CACTUS: 1.8
  KELP: 0.3
  DRIED_KELP: 1.2
  COCOA_BEANS: 2.5
  SWEET_BERRIES: 1.0
  GLOW_BERRIES: 2.0
  NETHER_WART: 4.5
  CHORUS_FRUIT: 3.5
  POPPED_CHORUS_FRUIT: 4.0
  CHORUS_FLOWER: 6.0
  BROWN_MUSHROOM: 1.5
  RED_MUSHROOM: 1.5
  MUSHROOM_STEM: 3.0
  CRIMSON_FUNGUS: 2.0
  WARPED_FUNGUS: 2.0
  VINE: 0.8
  WEEPING_VINES: 1.2
  TWISTING_VINES: 1.2
  LILY_PAD: 1.0
  SMALL_DRIPLEAF: 1.5
  BIG_DRIPLEAF: 2.0
  MOSS_BLOCK: 2.5
  MOSS_CARPET: 1.0
  SPORE_BLOSSOM: 8.0
  HANGING_ROOTS: 1.0
  AZALEA: 3.0
  FLOWERING_AZALEA: 4.0
  TORCHFLOWER_SEEDS: 5.0
  PITCHER_POD: 5.0
  HAY_BLOCK: 18.0

  # COMIDA
  BEEF: 4.0
  COOKED_BEEF: 6.0
  PORKCHOP: 4.0
  COOKED_PORKCHOP: 6.0
  CHICKEN: 3.0
  COOKED_CHICKEN: 5.0
  MUTTON: 3.5
  COOKED_MUTTON: 5.5
  RABBIT: 4.0
  COOKED_RABBIT: 6.5
  COD: 3.0
  COOKED_COD: 5.0
  SALMON: 3.5
  COOKED_SALMON: 5.5
  PUFFERFISH: 2.0
  TROPICAL_FISH: 6.0
  APPLE: 2.5
  HONEY_BOTTLE: 5.0

  # MOBS
  ROTTEN_FLESH: 0.8
  BONE: 1.5
  BONE_MEAL: 1.2
  STRING: 2.0
  SPIDER_EYE: 2.5
  FERMENTED_SPIDER_EYE: 4.0
  GUNPOWDER: 3.5
  ENDER_PEARL: 8.0
  BLAZE_ROD: 10.0
  BLAZE_POWDER: 5.0
  GHAST_TEAR: 15.0
  MAGMA_CREAM: 6.0
  MAGMA_BLOCK: 9.0
  SLIME_BALL: 4.0
  SLIME_BLOCK: 36.0
  PHANTOM_MEMBRANE: 8.0
  SHULKER_SHELL: 25.0
  WITHER_SKELETON_SKULL: 150.0
  FEATHER: 1.5
  LEATHER: 3.0
  INK_SAC: 2.0
  GLOW_INK_SAC: 5.0
  EGG: 1.0
  ARROW: 0.5
  TOTEM_OF_UNDYING: 250.0
  SCUTE: 20.0

  # MADERAS
  OAK_LOG: 2.0
  SPRUCE_LOG: 2.0
  BIRCH_LOG: 2.0
  JUNGLE_LOG: 2.2
  ACACIA_LOG: 2.2
  DARK_OAK_LOG: 2.5
  MANGROVE_LOG: 2.5
  CHERRY_LOG: 2.8
  CRIMSON_STEM: 3.0
  WARPED_STEM: 3.0
  STRIPPED_OAK_LOG: 2.5
  STRIPPED_SPRUCE_LOG: 2.5
  STRIPPED_BIRCH_LOG: 2.5
  STRIPPED_JUNGLE_LOG: 2.8
  STRIPPED_ACACIA_LOG: 2.8
  STRIPPED_DARK_OAK_LOG: 3.0
  STRIPPED_MANGROVE_LOG: 3.0
  STRIPPED_CHERRY_LOG: 3.2
  STRIPPED_CRIMSON_STEM: 3.5
  STRIPPED_WARPED_STEM: 3.5
  OAK_PLANKS: 0.8
  SPRUCE_PLANKS: 0.8
  BIRCH_PLANKS: 0.8
  JUNGLE_PLANKS: 0.9
  ACACIA_PLANKS: 0.9
  DARK_OAK_PLANKS: 1.0
  MANGROVE_PLANKS: 1.0
  CHERRY_PLANKS: 1.1
  CRIMSON_PLANKS: 1.2
  WARPED_PLANKS: 1.2
  OAK_LEAVES: 0.3
  SPRUCE_LEAVES: 0.3
  BIRCH_LEAVES: 0.3
  JUNGLE_LEAVES: 0.3
  ACACIA_LEAVES: 0.3
  DARK_OAK_LEAVES: 0.3
  MANGROVE_LEAVES: 0.4
  CHERRY_LEAVES: 0.4
  OAK_SAPLING: 1.5
  SPRUCE_SAPLING: 1.5
  BIRCH_SAPLING: 1.5
  JUNGLE_SAPLING: 2.0
  ACACIA_SAPLING: 2.0
  DARK_OAK_SAPLING: 2.5
  MANGROVE_PROPAGULE: 2.5
  CHERRY_SAPLING: 3.0
  STICK: 0.2

  # MINERALES
  COAL: 2.0
  CHARCOAL: 1.8
  COAL_BLOCK: 18.0
  IRON_INGOT: 6.0
  IRON_NUGGET: 0.7
  RAW_IRON: 5.0
  IRON_ORE: 5.5
  DEEPSLATE_IRON_ORE: 6.0
  IRON_BLOCK: 54.0
  COPPER_INGOT: 4.0
  RAW_COPPER: 3.5
  COPPER_ORE: 4.0
  DEEPSLATE_COPPER_ORE: 4.5
  COPPER_BLOCK: 36.0
  GOLD_INGOT: 8.0
  GOLD_NUGGET: 1.0
  RAW_GOLD: 7.0
  GOLD_ORE: 7.5
  DEEPSLATE_GOLD_ORE: 8.0
  GOLD_BLOCK: 72.0
  REDSTONE: 1.5
  REDSTONE_BLOCK: 13.5
  LAPIS_LAZULI: 1.5
  LAPIS_BLOCK: 13.5
  DIAMOND: 50.0
  DIAMOND_ORE: 55.0
  DEEPSLATE_DIAMOND_ORE: 60.0
  DIAMOND_BLOCK: 450.0
  EMERALD: 60.0
  EMERALD_ORE: 65.0
  DEEPSLATE_EMERALD_ORE: 70.0
  EMERALD_BLOCK: 540.0
  QUARTZ: 4.0
  AMETHYST_SHARD: 3.5
  AMETHYST_BLOCK: 28.0
  NETHERITE_SCRAP: 120.0
  NETHERITE_INGOT: 600.0
  FLINT: 1.5

  # PIEDRAS
  COBBLESTONE: 0.5
  STONE: 0.6
  SMOOTH_STONE: 0.7
  GRANITE: 0.8
  POLISHED_GRANITE: 1.0
  DIORITE: 0.8
  POLISHED_DIORITE: 1.0
  ANDESITE: 0.8
  POLISHED_ANDESITE: 1.0
  CALCITE: 0.7
  TUFF: 0.7
  DEEPSLATE: 0.7
  COBBLED_DEEPSLATE: 0.6
  POLISHED_DEEPSLATE: 1.0
  DEEPSLATE_TILES: 1.2
  DEEPSLATE_BRICKS: 1.2
  DRIPSTONE_BLOCK: 1.0
  POINTED_DRIPSTONE: 0.6
  OBSIDIAN: 15.0
  GRAVEL: 0.8
  SAND: 0.8
  RED_SAND: 1.0
  SANDSTONE: 1.2
  CUT_SANDSTONE: 1.4
  CUT_SANDSTONE_SLAB: 0.7
  SANDSTONE_SLAB: 0.6
  SANDSTONE_STAIRS: 1.5
  RED_SANDSTONE: 1.3
  CUT_RED_SANDSTONE: 1.5
  CUT_RED_SANDSTONE_SLAB: 0.7
  RED_SANDSTONE_SLAB: 0.6
  RED_SANDSTONE_STAIRS: 1.6
  BASALT: 0.9
  BLACKSTONE: 0.9
  NETHERRACK: 0.4
  END_STONE: 1.2
  END_STONE_BRICKS: 1.5
  PURPUR_BLOCK: 2.0
  PURPUR_SLAB: 1.0
  PURPUR_STAIRS: 2.2

  # CONSTRUCCION
  DIRT: 0.4
  GRASS_BLOCK: 0.8
  PODZOL: 0.9
  MYCELIUM: 1.2
  COARSE_DIRT: 0.6
  MUD: 0.7
  PACKED_MUD: 0.9
  SNOWBALL: 0.3
  SNOW_BLOCK: 1.5
  ICE: 1.2
  PACKED_ICE: 3.0
  BLUE_ICE: 9.0
  GLASS: 1.5
  GLASS_PANE: 0.6
  TERRACOTTA: 1.5
  BRICKS: 3.0
  STONE_BRICKS: 2.5
  CRACKED_STONE_BRICKS: 2.2
  CHISELED_STONE_BRICKS: 2.8
  PRISMARINE: 4.0
  PRISMARINE_BRICKS: 4.5
  DARK_PRISMARINE: 5.0
  PRISMARINE_SHARD: 2.0
  PRISMARINE_CRYSTALS: 3.0
  SEA_LANTERN: 12.0
  SPONGE: 40.0
  BEACON: 1500.0
  CONDUIT: 900.0
